### ISSUE TITLE
ImportError: cannot import name u2f_v2

### ISSUE THREAD

**Issue by theparadoxer02** [gavinwahl/django-u2f#23]
I tried to install django-u2f followed all the procedure then when i ran the command 
python manage.py syncdb 

the error i am getting it 
```
from django_u2f import views as u2f_views
File "/home/r3dt3am/Desktop/projects/U2F/venv/local/lib/python2.7/site-packages/django_u2f/views.py", line 24, in <module>
from u2flib_server import u2f_v2 as u2f
ImportError: cannot import name u2f_v2

```

**Comment by gavinwahl** [comment]
python-u2flib-server version 5.0.0 is incompatible. I'm working on fixing this in the django-1.11 branch

**Comment by gavinwahl** [comment]
Ok, I have released version 0.2.0 which should work. Let me know if there are any issues!
